# This is a basic workflow to help you get started with Actions

name: TEST - OpenAPI

# Controls when the workflow will run
on:
  push:
    branches: [ feat/open-api ]
  pull_request:
    branches: [ feat/open-api ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current repo
        uses: actions/checkout@v2
      - name: Checkout part env repo
        uses: actions/checkout@v2
        with:
          repository: place-labs/partner-environment 
          path: main
      - name: Spin up PlaceOS
        working-directory: ./main
        run: ./placeos start --verbose
        env:
          PLACE_EMAIL: support@place.tech
          PLACE_PASSWORD: development
      - name: Echo
        run: |
            va=$( curl --location --request POST "https://localhost:8443/auth/oauth/token?grant_type=password&username=support@place.tech${{ secrets.URL_PASSWORD }}" -k)
            echo "MN=$va" >> "$GITHUB_ENV"
      - name: Set Auth Token
        run: |
            token=$(  curl --location --request POST "https://localhost:8443/auth/oauth/token?grant_type=password&username=support@place.tech${{ secrets.URL_PASSWORD }}" -k | jq -r '.access_token')
            echo "ORG=$token" >> "$GITHUB_ENV"
      - name: Echo
        run: echo "$ORG"
