# This is a basic workflow to help you get started with Actions

name: TEST - OpenAPI

# Controls when the workflow will run
on:
  push:
    branches: [ feat/open-api ]
  pull_request:
    branches: [ feat/open-api ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current repo
        uses: actions/checkout@v2
      - name: Checkout part env repo
        uses: actions/checkout@v2
        with:
          repository: place-labs/partner-environment 
          path: main
      - name: Spin up PlaceOS
        working-directory: ./main
        run: ./placeos start --verbose
        env:
          PLACE_EMAIL: support@place.tech
          PLACE_PASSWORD: development
      - name: Set Auth Token
        run: |
            token=$( curl --location --request POST 'https://localhost:8443/auth/oauth/token?grant_type=password&username=support@place.tech&password=development&client_id=b52e653071c45353dbff4e8f47d51cdf' | jq -r '.access_token')
            echo "AUTH_TOKEN=$token" >> "$GITHUB_ENV"
        run: echo "$AUTH_TOKEN"
